# Generated by Django 4.1.2 on 2022-12-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
